# This file was generated by release.py
require 'formula'
class Ws < Formula
  homepage 'https://github.com/yhat/ws'
  version '0.1'
  if Hardware.is_64_bit?
    url 'https://github.com/yhat/ws/releases/download/v0.1/ws_darwin_amd64.zip'
    sha1 '698ba51bf5b18f4823352fe4093a6a258f941300'
  else
    url 'https://github.com/yhat/ws/releases/download/v0.1/ws_darwin_386.zip'
    sha1 'b086a8577a15d3b124cb8bc3693826016b7eed73'
  end
  def install
    bin.install 'ws'
  end
end
